name: CodeQL Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./HelloWorld/.github/workflows
/main.yml

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v1
